include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-shadowsocks-rust
PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_LICENSE:=GPL-3.0
PKG_MAINTAINER:=Jove Yu <yushijun110@gmail.com>

LUCI_TITLE:=LuCI support for Shadowsocks Rust
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
LUCI_LANGUAGES:=zh_Hans

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
